config/routes.rb
Rails.application.routes.draw do
  # root to: 'users#profile'
  root to:'searches#pick_location', as: :landing_page
  devise_for :users
  #searches controller
  get 'search/result&:addressvalue', to:'searches#show_search_results'
  get 'band/page&:name&:id', to: 'searches#band_search_result'
  # bands controller
  get 'band/page/:id', to:'bands#show' , as: :band
  get 'band/page/redirect', to:"bands#redirect_band", as: :redirect_band
  patch 'band/page/update', to:'bands#update'
  get 'permission/denied', to:'bands#error_page'

  namespace :api do
      namespace :v1 do
        # band tour dates
        get 'band/current/markers', to:'tourdatemodelupdates#current_markers'
        post 'band/page/marker/create', to: 'tourdatemodelupdates#create_tour_date'
        delete 'delete/date', to: 'tourdatemodelupdates#delete_tour_date'
        # band info Field
        patch 'band/page/update/name', to:'bandmodelupdates#update_band_name'
        patch 'band/page/update/about', to:'bandmodelupdates#update_band_about'
        patch 'band/page/update/price', to:'bandmodelupdates#update_band_price'
        patch 'band/page/update/requirements', to:'bandmodelupdates#update_band_requirements'
        patch 'band/page/update/profilepic', to:'bandmodelupdates#update_band_profilepic'
        #searches info
        get 'available/gigs', to: "searchesinfo#all_gigs"
        get 'allbands/:id', to: 'searchesinfo#all_bands'
        get 'current/markers/search/:band_id', to: 'searchesinfo#current_band_gig'
      end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :user
  has_many :tour_dates
end

app/models/tour_date.rb
class TourDate < ApplicationRecord
  belongs_to :band
end

app/models/user.rb
class User < ApplicationRecord
  has_one :band
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :create_band_object

  private
  def create_band_object
    Band.create(user_id: User.last.id)
  end
end

app/controllers/Api/V1/bandmodelupdates_controller.rb
class Api::V1::BandmodelupdatesController < ApplicationController
  def update_band_name
    @band = Band.find_by(user_id: current_user.id)
    @band.update(name: params[:name])
  end

  def update_band_about
    @band = Band.find_by(user_id: current_user.id)
    @band.update(about: params[:about])
  end

  def update_band_price
    @band = Band.find_by(user_id: current_user.id)
    @band.update(price: params[:price])
  end

  def update_band_requirements
    @band = Band.find_by(user_id: current_user.id)
    @band.update(requirements: params[:requirements])
  end

  def update_band_profilepic
    @band = Band.find_by(user_id: current_user.id)
    @band.update(profilepic: params[:profilepic])
  end
end

#about: params[:about], price: params[:price], radius: params[:radius],
#requirements: params[:requirements], facebook: params[:facebook], twitter: params[:twitter], soundcloud: params[:soundcloud],
#spotify:params[:spotify], profile_pic:params[:profile_pic] -->

app/controllers/Api/V1/searchesinfo_controller.rb
class Api::V1::SearchesinfoController < ApplicationController
  def search_result
  end

  def all_gigs
    @gigs = TourDate.all
    render json: @gigs
  end

  def current_band_gig
    @gigs = TourDate.where(band_id:params[:band_id]).all
    render json: @gigs
  end

  def all_bands
    @bands = Band.find_by(id: params[:id])
    render json: @bands
  end
end

app/controllers/Api/V1/tagmodelupdates_controller.rb
class Api::V1::TagmodelupdatesController < ApplicationController
end

app/controllers/Api/V1/tourdatemodelupdates_controller.rb
class Api::V1::TourdatemodelupdatesController < ApplicationController
  def create_tour_date
    @Tourdate = TourDate.create(band_id: current_user.id)
    @Tourdate.update(Longitude: params[:Longitude],Latitude:params[:Latitude] , address: params[:address], date: params[:date])
  end

  def current_markers
    @tourdate = TourDate.where(band_id: current_user.id).all
    render json: @tourdate
  end

  def delete_tour_date
    @tourdate = TourDate.where(band_id: current_user.id).find_by(id: params[:id])
    @tourdate.delete
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
before_action :authenticate_user!
  def redirect_band
    redirect_to '/band/page/1'
  end

  def show
    if (params[:id].to_s == current_user.id.to_s)
      @band = Band.find_by(user_id: params[:id])
      @tourdate = []
      TourDate.where(band_id: params[:id]).find_each do |gig|
        @tourdate << gig
      end
    else
      redirect_to '/permission/denied'
    end
  end
  
  def error_page
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def pick_location
  end

  def show_search_results
  end

  def band_search_result
    if user_signed_in? && current_user.id.to_s == params[:id].to_s
        redirect_to '/band/page/' + params[:id]
    else
      @band = Band.find_by(id: params[:id])
      @tourdate = TourDate.where(band_id: params[:id]).all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = current_user
    render 'users/profile'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/error_page.html.erb
<iframe width="560" height="315" src="https://www.youtube.com/embed/ygr5AHufBN4?autoplay=1" frameborder="0" allowfullscreen></iframe>

app/views/bands/show.html.erb
<!--- page starts here -->
<div class="tile is-ancestor">
  <div class="tile is-1 is-vertical">
  </div>
  <div class="tile is-2 is-vertical is-parent about-box">
    <div class="tile is-child">
      <img src="http://www.freeiconspng.com/uploads/save-icon-20.png" class="save-button hidden" id="save_name">
      <img src="http://image.flaticon.com/icons/svg/61/61456.svg" class="edit-button" id="edit_name" onclick="startForm(this)">
    <br>
    <center>
      <h3 class="strong" id="static_name"> <%= @band.name %>
      </h3>
    </center>
    <input class="hidden input" type=text id="band_name" placeholder="update field">
    <br>
    <!-- band profile picture -->
    <img class="image is-256x256" src="<%= @band.profilepic %>" >
    <br>
    <!-- band about -->
    <img src="http://www.freeiconspng.com/uploads/save-icon-20.png" class="save-button hidden" id="save_about">
    <img src="http://image.flaticon.com/icons/svg/61/61456.svg" class="edit-button" id="edit_about" onclick="startForm(this)">
    <center>
      <h3 class="strong">
        About
      </h3>
    </center>
      <div class="text-box" id="static_about">
        <%= @band.about %>
      </div>
      <textarea class="hidden textarea" id="band_about" placeholder="update field"> </textarea>
    </div>
  </div>
  <div class="tile is-1 is-vertical is-parent">
  </div>
  <div class="tile is-horizontal is-6 is-parent">
    <div class="tile is-child">
      <img src="http://www.freeiconspng.com/uploads/save-icon-20.png" class="save-button invisible">
      <center> <h1 class="strong"> Band Info </h1> </center>
      <div class="tile is-child">
          <hr class="style-one"> </hr>
      </div>
      <div class="tile is-child">
        <img src="http://www.freeiconspng.com/uploads/save-icon-20.png" class="save-button hidden" id="save_requirements">
        <img src="http://image.flaticon.com/icons/svg/61/61456.svg" class="edit-button" id="edit_requirements" onclick="startForm(this)">
        <center ><h2 class="strong subtitle is-3"> Band Requirements </h2> </center>
        <br>
        <div id="static_requirements">
          <%= @band.requirements %>
        </div>
        <textarea class="hidden textarea" id="band_requirements" placeholder="update field"> </textarea>
      </div>
      <br>
      <div class="tile is-child">
        <img src="http://www.freeiconspng.com/uploads/save-icon-20.png" class="save-button hidden" id="save_price">
        <img src="http://image.flaticon.com/icons/svg/61/61456.svg" class="edit-button" id="edit_price" onclick="startForm(this)">
        <center> <p class="strong subtitle is-3"> Price  -
          <span class="subtitle is-4" id="static_price">
            <%=@band.price%>
          </span>
          <input class="hidden input" type=number id="band_price" placeholder="update field">
          <span class="subtitle is-4">
            €*
          </span>
        </center> </p>
      </div>
      <br>
      <img src="http://www.dropitproject.com/categories/Eightyshades/Eightyshades08.png" class="add_sign" id="add_date">
      <br>
      <div class="tile is-child map" id="tourmap">
      </div>
      <br>
      <div class="tile is-parent">
        <div class="tile is-child is-4">
        </div>
        <div class="tile is-child ">
          <a class="button contact-us orange"> Contact Us!</a>
        </div>
      </center>
      </div>
    </div>
  </div>
  <div class="tile is-2 is-vertical is-parent">
  </div>
</div>

<!-- blue column lool --->
<div class="tile is-ancestor">
  <div class="tile is-parent is-1">
  </div>
  <div class="tile is-parent is-2 about-box">
  <div class="tile is-child">
  </div>
  </div>
</div>
<div class="tile is-ancestor">
  <div class="tile is-parent is-1">
  </div>
  <div class="tile is-parent is-2 about-box">
  <div class="tile is-child">
  </div>
  </div>
</div>
<div class="tile is-ancestor">
  <div class="tile is-parent is-1">
  </div>
  <div class="tile is-parent is-2 about-box">
  <div class="tile is-child">
  </div>
  </div>
</div>
<div class="tile is-ancestor">
  <div class="tile is-parent is-1">
  </div>
  <div class="tile is-parent is-2 about-box">
  <div class="tile is-child">
  </div>
  </div>
</div>




<!--- insert profile images -->
<div class="field profilepic" id="profilepic">
  <h3> profile picture
    <img src="http://image.flaticon.com/icons/svg/61/61456.svg" class="edit-button" id="edit_profilepic">
    <img src="http://www.freeiconspng.com/uploads/save-icon-20.png" class="save-button hidden" id="save_profilepic">
  </h3>
  <div class="edit">
    <input class="hidden" type=text id="band_profilepic" placeholder="update field">
  </div>
  <div class="static" id="static_profilepic">
    <p> <%= @band.profilepic %> </p>
  </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD61szX4DwMm4p0JkBGN_bBtZUSniJm3bk&libraries=places" defer>
</script>

<!-- modal to add tours -->
<div class="modal" id="map_modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Add Tour dates here</p>
      <button id="modal_delete" class="delete"></button>
    </header>
    <section class="modal-card-body">
      <div class="columns">
        <div class="column">
          <input type=text id="insert_gig_place">
          <input type="submit" value="search" id="search_location_modal">
          <input id="date_picker_modal" type="date"/>
          <div class="map" id="tourmap_modal"> </div> <!-- map inside of the modal  -->
        </div>
        <div class="column">
          <center>
            <img src="http://www.dropitproject.com/categories/Eightyshades/Eightyshades08.png" class="add_sign" id="add_gig">
            <span class="subtitle is-5 strong"> Add Gig </span>
            <br>
            <br>
            <ul id="list_of_gigs">
              <%@tourdate.each do |gig|%>
                <li class="gig_date" id="<%=gig.id%>" onmouseover="ShowDeleteButton(this)" onmouseout="HideDeleteButton(this)">
                  <%= gig.address %> ( <%= gig.date %> )
                  <img class="delete_button_modal hidden" src="http://image.flaticon.com/icons/png/128/70/70287.png" id="deletedatemodal_<%=gig.id%>" onclick="removeDate(this)" >
                </li>
                <br>
              <%end%>
            </ul>
          </center>
        </div>
      </div>
    </section>
    <footer class="modal-card-foot">
      <a class="button is-primary" id="save_added_gig">Save changes</a>
      <a class="button" id="modal_cancel">Cancel</a>
    </footer>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeTour</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application'%>
  </head>
  <body>
<!-- navigation menu -->
<nav class="nav has-shadow columns">
  <div class="column is-1">
  </div>
  <div class="container">
    <img class="logo nav-item" src="/logo/logo.png">
  </div>
  <div class="container">
  </div>
  <span class="notice container nav-item"><%= notice %></span>
  <div class="container">
    <span class="nav-item is-tab is-active is-right"><%= link_to 'Home', landing_page_path, method: 'GET'%> </span>
  <% if user_signed_in? %>
    <span class="nav-item is-tab"><%= link_to 'Band Page', redirect_band_path, method: 'GET' %>
    <span class="nav-item is-tab"><%= link_to 'Sign out', destroy_user_session_path, method: 'DELETE' %>
    </span>
  <% else %>
    <span class="nav-item is-tab"> <%= link_to 'Log in', new_user_session_path %></span>
    <span class="nav-item is-tab is-right"> <%= link_to 'Sign up', new_user_registration_path %> </span>
  <% end %>
 </div>
</nav>
<!-- end of navigation menu -->
    <!-- Devise alerts -->
    <p class="alert"><%= alert %></p>
    <!-- Devise alerts -->
    <%= yield %>
  </body>
</html>

app/views/searches/band_search_result.html.erb
<div class="tile is-ancestor">
  <div class="tile is-1 is-vertical">
  </div>
  <div class="tile is-2 is-vertical is-parent about-box">
    <div class="tile is-child">
    <h3 class="strong"> <center> <%= @band.name %> </center> </h3>
    <br>
    <img class="image is-256x256" src="<%= @band.profilepic %>" >
    <br>
    <center> <h3 class="strong"> About </h3> </center>
      <div class="text-box"> <%= @band.about %> </div>
    </div>
  </div>
  <div class="tile is-1 is-vertical is-parent">
  </div>
  <div class="tile is-horizontal is-6 is-parent">
    <div class="tile is-child">
      <center> <h1 class="strong"> Band Info </h1> </center>
      <div class="tile is-child">
          <hr class="style-one"> </hr>
      </div>
      <div class="tile is-child">
        <center ><h2 class="strong subtitle is-3"> Band Requirements </h2> </center>
        <br>
        <%= @band.requirements %>
      </div>
      <br>
      <div class="tile is-child">
        <center> <p class="strong subtitle is-3"> Price  -
          <span class="subtitle is-4"> <%=@band.price%>€*
          </spa>
        </center></p>
      </div>
      <br>
      <div class="tile is-child map" id="searched_band_map">
      </div>
      <br>
      <div class="tile is-parent">
        <div class="tile is-child is-4">
        </div>
        <div class="tile is-child ">
          <a class="button contact-us orange"> Contact Us!</a>
        </div>
      </center>
      </div>
    </div>
  </div>
  <div class="tile is-2 is-vertical is-parent">
  </div>
</div>

<!-- blue column lool --->
<div class="tile is-ancestor">
  <div class="tile is-parent is-1">
  </div>
  <div class="tile is-parent is-2 about-box">
  <div class="tile is-child">
  </div>
  </div>
</div>
<div class="tile is-ancestor">
  <div class="tile is-parent is-1">
  </div>
  <div class="tile is-parent is-2 about-box">
  <div class="tile is-child">
  </div>
  </div>
</div>
<div class="tile is-ancestor">
  <div class="tile is-parent is-1">
  </div>
  <div class="tile is-parent is-2 about-box">
  <div class="tile is-child">
  </div>
  </div>
</div>
<div class="tile is-ancestor">
  <div class="tile is-parent is-1">
  </div>
  <div class="tile is-parent is-2 about-box">
  <div class="tile is-child">
  </div>
  </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD61szX4DwMm4p0JkBGN_bBtZUSniJm3bk&libraries=places,geometry" defer>
</script>

app/views/searches/pick_location.html.erb
<div class="columns">
  <div class="column">
    <center> <img src="/background/cover.jpg"> </center>
  <div>
</div>
<center>
  <h1> Look for a Band to play on your next event!</h1>
</center>
<br>
<div class="columns">
  <div class="column is-3">
  </div>
  <div class="column is-5">
    <input class="input" type="text" placeholder="Insert the location of your event" id="search_location_input">
  </div>
  <div class="column">
    <input class="button" type="submit" value="Search" id='search_location_submit'>
  </div>
  <div class="column is-3">
  </div>
</div>
























<!-- <div class="search_location">
    <div>
      <input type="text" name="search_location" id="search_location_input">
    </div>
    <div id="search_location_button">
      <input type="submit" value="Submit" >
    </div>
</div>
<div class="map" id="pick_location">
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD61szX4DwMm4p0JkBGN_bBtZUSniJm3bk&libraries=places" defer async>
</script> -->

app/views/searches/show_search_results.html.erb
<div class="columns">
  <div class="column is-1">
  </div>
  <div class="column">
    <div class="columns">
      <div class="column is-10">
        <input class="input" type="text" name="search_location" id="search_location_input2">
      </div>
      <div class="column">
        <input class="button" type="submit" value="Search" id="submit_search2">
      </div>
    </div>
  <!-- search results go below -->
  <div class="search_results">
  </div>
</div>
  <!--- search result end ----->
  <div class="column">
    <div class="map" id="querymap">
    </div>
  </div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD61szX4DwMm4p0JkBGN_bBtZUSniJm3bk&libraries=places,geometry" defer>
</script>

app/views/users/profile.html.erb
<h2><%= current_user.username %>!</h2>

<p>
<strong>Email:</strong> <%= current_user.email %>
</p>